### ISSUE TITLE
Add support for provenance

### ISSUE THREAD

**Issue by simoneb** [nearform-actions/optic-release-automation-action#285]
https://github.blog/2023-04-19-introducing-npm-package-provenance/

Things to consider:

- does it work on older npm versions? probably not

**Comment by AlanSl** [comment]
Regarding the "older versions of NPM" question: 

Running `npm publish --provenance` in 9.4 (before the release in 9.5) just ignores the flag, it doesn't cause it to fail. NPM 9.5.1 is already the default in `ubuntu-latest` so most CI jobs should be 

I'm assuming we want provenance to be an opt-in option defined something like this?

```yml
      - uses: nearform-actions/optic-release-automation-action
        with:
          semver: ${{ github.event.inputs.semver }}
          commit-message: 'chore: release {version}'
          provenance: true
```

So we could just ignore NPM version, but maybe we want to abort if a user opted in to provenance and doesn't realise their CI is using a too-old version of NPM, rather than letting the publish succeed and the provenance aspect fail silently? With something like this maybe:

```js
if (inputs['provenance']) {
  const npmVersion = getNpmVersion()
  if (!semver.satisfies(npmVersion, '>=9.5.0') {
    throw new Error(`Provenance option requires action to run on NPM >=9.5.0. You are using NPM ${npmVersion}`)
  }
}
```
